// File: pmux4.v
// Generated by MyHDL 0.10
// Date: Mon Jul  9 22:24:43 2018


`timescale 1ns/10ps

module pmux4 (
    clk,
    out,
    ins_in_d,
    ins_in_c,
    ins_in_a,
    ins_in_b,
    sels_sel_a,
    sels_sel_b,
    sels_sel_c,
    sels_sel_d
);


input clk;
output out;
reg out;
input ins_in_d;
input ins_in_c;
input ins_in_a;
input ins_in_b;
input sels_sel_a;
input sels_sel_b;
input sels_sel_c;
input sels_sel_d;




always @(sels_sel_a, sels_sel_b, sels_sel_c, sels_sel_d, ins_in_a, ins_in_b, ins_in_c, ins_in_d) begin: PMUX4_MAKE_OUT
    if (sels_sel_a) begin
        out <= ins_in_a;
    end
    else if (sels_sel_b) begin
        out <= ins_in_b;
    end
    else if (sels_sel_c) begin
        out <= ins_in_c;
    end
    else if (sels_sel_d) begin
        out <= ins_in_d;
    end
    else begin
        out <= 1'b0;
    end
end

endmodule
